version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - WEATHERAPI_KEY=${WEATHERAPI_KEY}
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - MONGO_URI=mongodb://mongo:27017/emergency-ai
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: